### ISSUE TITLE
It is not possible to send larger amounts of Eth.

### ISSUE THREAD

**Issue by lazyanubis** [nikolas-con/ic-evm-tx#4]
I noticed that the value type in the transaction is a 64-bit number, which seems to support a maximum of 18.xx Eth. Clearly, if someone wants to send more Eth, it would not be possible to do so.

Max Number(64bit)：18_446_744_073_709_551_615

1Eth = 10^18 Wei

**Comment by LiveDuo** [comment]
Hey @AnubisAwooo, thanks for reporting the issue.

It's indeed a problem with the transaction structs from [lib/src/transaction.rs#L407](https://github.com/nikolas-con/ic-evm-sign/blob/master/lib/src/transaction.rs#L407).

We'll need some time to get back to fixing the issue as we are working on other stuff right now. Since it's a trivial issue to fix if you are looking use the library at some point this week, feel free to submit a PR. I'll review and merge soon enough.
